services:
  mongodb:
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
    command: pnpm api dev
