packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@babel/core": "^7.24.7"
  "@logdna/tail-file": "^4.0.2"
  "@mantine/charts": "^7.12.2"
  "@mantine/core": "7.12.2"
  "@mantine/form": "^7.12.2"
  "@mantine/hooks": "7.12.2"
  "@mantine/notifications": "^7.16.3"
  "@nestjs/cli": "^10.4.9"
  "@nestjs/common": "^11.0.7"
  "@nestjs/config": "^4.0.2"
  "@nestjs/core": "^11.1.8"
  "@nestjs/event-emitter": "^2.1.1"
  "@nestjs/mongoose": "^10.1.0"
  "@nestjs/platform-express": "^11.0.7"
  "@nestjs/schedule": "^4.1.2"
  "@nestjs/schematics": "^10.2.3"
  "@nestjs/swagger": "^7.4.2"
  "@nestjs/testing": "^10.4.15"
  "@swc/core": "^1.10.14"
  "@tabler/icons-react": "^3.6.0"
  "@types/express": "^5.0.5"
  "@types/node": "^20.14.8"
  "@types/nodemailer": "^6.4.16"
  "@types/react": "19.2.5"
  "@types/supertest": "^6.0.0"
  "@typescript-eslint/eslint-plugin": "^8.0.0"
  "@typescript-eslint/parser": "^8.0.0"
  "@vitest/coverage-v8": "3.0.5"
  "axios": "^1.7.7"
  "babel-loader": "^9.1.3"
  "class-transformer": "^0.5.1"
  "class-validator": "^0.14.1"
  "clsx": "^2.1.1"
  "date-fns": "^3.6.0"
  "dockerode": "^4.0.2"
  "eslint": "^8.57.0"
  "eslint-config-next": "^14.2.11"
  "eslint-config-prettier": "^9.1.0"
  "eslint-plugin-import": "^2.29.1"
  "eslint-plugin-prettier": "^5.0.0"
  "gitmoji-cli": "^9.4.0"
  "maxmind": "^4.3.22"
  "mongoose": "^8.6.1"
  "next": "14.2.4"
  "nodemailer": "^6.9.15"
  "postcss": "^8.4.38"
  "postcss-preset-mantine": "1.17.0"
  "postcss-simple-vars": "^7.0.1"
  "prettier": "^3.3.3"
  "prettier-plugin-organize-imports": "^4.0.0"
  "purify-ts": "^2.1.0"
  "react": "19.2.0"
  "react-dom": "18.3.1"
  "reflect-metadata": "^0.2.2"
  "rxjs": "^7.8.1"
  "source-map-support": "^0.5.21"
  "stylelint": "^16.25.0"
  "stylelint-config-standard": "^36.0.1"
  "stylelint-prettier": "^5.0.2"
  "supertest": "^7.0.0"
  "swr": "^2.2.5"
  "ts-loader": "^9.4.3"
  "ts-node": "^10.9.1"
  "tsconfig-paths": "^4.2.0"
  "turbo": "2.0.9"
  "typescript": "5.5.2"
  "unplugin-swc": "^1.5.1"
  "vite-tsconfig-paths": "^5.1.4"
  "vitest": "^3.0.5"
