export enum Events {
  BAN_CREATION_REQUESTED = "ban.creation.requested",
  BAN_CREATION_DONE = "ban.creation.done",
  CONFIG_CREATION_DONE = "config.creation.done",
  CONFIG_UPDATE_DONE = "config.update.done",
  CONFIG_REMOVE_DONE = "config.remove.done",
  MATCH_CREATION_REQUESTED = "match.creation.requested",
  MATCH_CREATION_DONE = "match.creation.done",
  UNBAN_CREATE_REQUESTED = "unban.create.requested",
  FIREWALL_DENY = "firewall.deny",
  FIREWALL_ALLOW = "firewall.allow",
  NOTIFY = "notify",
  NOTIFY_CONFIG_CREATION_DONE = "notify.config.creation.done",
  NOTIFY_CONFIG_UPDATE_DONE = "notify.config.update.done",
  NOTIFY_CONFIG_DELETE_DONE = "notify.config.delete.done",
}
