name: Build Docker CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-build:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Build api docker image
        run: docker compose build api

      - name: Build web docker image
        run: docker compose build web

      - name: Start containers
        run: docker compose up -d && sleep 30

      - name: Check api container
        run: |
          docker compose logs api | grep -q "Nest application successfully started"
          docker ps -a | grep "banalize-api" | grep -q "Up"

      - name: Check web container
        run: |
          docker compose logs web | grep -q "Ready in "
          docker ps -a | grep "banalize-web" | grep -q "Up"

      - name: Stop containers
        run: docker compose down
